spring:
  profiles:
    group:
      local: local-db, local
---
spring:
  config:
    activate:
      on-profile: local-db
  datasource:
    url: [url]
    username: [username]
    password: [password]
    driver-class-name: org.postgresql.Driver
---
spring:
  config:
    activate:
      on-profile: local
  flyway:
    enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: [client-id]
            client-secret: [client-secret]
            scope:
              - profile
              - email
  servlet:
    multipart:
      enabled: true
      max-file-size: 512MB
      max-request-size: 512MB
server:
  port: [port]
s3:
  region: [region]
  bucket: [bucket]
  access-key: [access-key]
  secret-key: [secret-key]
environment:
  local-storage-home: [local-storage-home]