spring:
  profiles:
    group:
      local: local-db, local
---
spring:
  config:
    activate:
      on-profile: local-db
  datasource:
    url: [url]
    username: [username]
    password: [password]
    driver-class-name: org.postgresql.Driver
---
spring:
  config:
    activate:
      on-profile: local
  flyway:
    enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: [client-id]
            client-secret: [client-secret]
            scope:
              - profile
              - email
server:
  port: [port]